import Head from 'next/head'
import { ContentSide } from '../components/contentSide'
import { Footer } from '../components/Fixed Components/Footer'
import { NavBar } from '../components/Fixed Components/NavBar'
import { LeftSide } from '../components/leftSide'
import { RightSide } from '../components/rightSide'

export default function Home() {
  return (
    <>
      <Head>
        <title>Techinika</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className='w-full bg-gray-50'>
        <NavBar />
        <div className='w-8/12 mt-4 mb-4 flex flex-row mx-auto gap-4 items-start'>
          <LeftSide />
          <ContentSide />
          <RightSide />
        </div>
        <Footer />
      </div>
    </>
  )
}
