import { useRouter } from 'next/router';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Link from "next/link";
import Head from 'next/head';
import { LeftSide } from '../components/leftSide';
import { ProfileContent } from '../components/MiddleContents/ProfileContent';

export async function getStaticProps({ locale }) {
    return {
      props: {
        ...(await serverSideTranslations(locale, ['common'])),
      },
    };
}

export default function Profile() {
    const { locales } = useRouter();
    const { t } = useTranslation('common');
    return (
        <>
            <Head>
                <title>Techinika - Profile</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className='fixed left-0 h-screen flex items-center justify-center flex-col gap-4 p-1'>
                {locales.map(l => (
                <Link href="/profile" locale={l} key={l} >
                    <p className="p-2 text-white rounded-full bg-blue-900 cursor-pointer">{l}</p>
                </Link>
                ))}
            </div>

            <div className='w-8/12 mt-4 mb-4 flex flex-row mx-auto gap-4 items-start'>
                <LeftSide t={t}/>
                <ProfileContent t={t}/>
            </div>
        
        </>
    )
}